---
langs: [fr_FR, en_US, es_ES, de_DE]
baseurl: "/designImgSwitch" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- vendor
plugins:
- jekyll-paginate
- jekyll-seo-tag
title: "designImgSwitch"
description: "Ceci est la documentation du plugin designImgSwitch de la solution domotique Jeedom."
author: "Mips2648"
image: https://www.jeedom.com/site/logo.png
twitter:
  username: Jeedom_domotic
social:
  name: Jeedom
  links:
    - https://twitter.com/Jeedom_domotic
    - https://www.facebook.com/Jeedom-249936178537210/
    - https://github.com/jeedom